sever:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.horace.springcloud.entities
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml

spring:
  application:
    name: microservi